redis:
  center:
    cluster: true
    TLSConfig:
      InsecureSkipVerify: true
    universal:
      # 地址
      addrs:
        - "clustercfg.streamingx-redis-formal.jis2bf.usw2.cache.amazonaws.com:6582"
      # DB
      # Password  # 密码
      # maxRetries
      # minRetryBackoff
      # maxRetryBackoff
      # dialTimeout
      # readTimeout
      # writeTimeout
      # poolSize
      # minIdleConns
      # maxConnAge
      # poolTimeout
      # idleTimeout
      # idleCheckFrequency

      # maxRedirects
      # readOnly
      # routeByLatency
      # routeRandomly

      # masterName
